YahooFuriganaAPI 用の .py ファイルを作成 & 切り出し
mizo0203/google-home-shiritori pull request #46
Opened 2019-03-23 03:37 UTC by mizo0203

* YahooFuriganaAPI 用の .py ファイルを作成 & 切り出し
* 標準ライブラリと Third-Party ライブラリの import 文を１行空ける

2019-03-23 12:11 UTC, hayatedayon requested changes

2019-03-23 12:11 UTC, hayatedayon commented on tests/test_yahooapis.py
> +# Copyright 2018 [name of copyright owner]
反映漏れです。

2019-03-23 12:11 UTC, hayatedayon commented on yahooapis.py
> +    for tmp in HIRAGANA_TO_KATAKANA.keys():
入力が”ひらがな”のみの場合、９０文字以下なら、入力文字をforで回してdictで変換したほうが効率よさそうな気がします。

2019-03-23 13:36 UTC, mizo0203 commented on tests/test_yahooapis.py
> +# Copyright 2018 [name of copyright owner]
修正します

2019-03-23 13:40 UTC, mizo0203 commented on yahooapis.py
> +    for tmp in HIRAGANA_TO_KATAKANA.keys():
修正します

2019-05-04 10:50 UTC, hayatedayon approved these changes

2019-05-04 10:50 UTC, merged